[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache_foundry"

# Solidity compiler settings
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

# EVM version
evm_version = "paris"

# Test settings
verbosity = 3

[fuzz]
runs = 256

# Formatter settings
[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"

# RPC endpoints
[rpc_endpoints]
monad_testnet = "https://testnet-rpc.monad.xyz"

# Etherscan settings (for verification)
[etherscan]
monad_testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://testnet.monadexplorer.com/api" }

