# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: monad-irc-indexer
description: Real-time indexer for Monad IRC events

networks:
  - id: 10143
    rpc_config:
      url: https://testnet-rpc.monad.xyz
    start_block: 44372794
    contracts:
      - name: MonadIRC
        address:
          - "0x99ff09C8163822c34A4d91D842B03af42A610aAC"
        abi_file_path: ./abis/MonadIRC.json
        handler: ./src/eventHandlers.ts
        events:
          - event: ChannelCreated(string channelName, address indexed creator, uint256 timestamp)
            field_selection:
              transaction_fields:
                - hash
          - event: MessageSent(bytes32 indexed msgHash, address indexed sender, string channel, uint256 timestamp)
            field_selection:
              transaction_fields:
                - hash

# Enable preload optimizations for better performance
preload_handlers: true
